#############################################################################
# Generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#  May 15, 2019 10:54:29 PM +0530  platform: Windows NT
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join V:/ {edd project 2019 jan} {edd project modules} {advance option - view databases} adv1.png]} {user image} user {}}
        {{[file join V:/ {edd project 2019 jan} {edd project modules} {advance option - view databases} adv2.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Captain Howdy} -size 13 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Bodoni MT Black} -size 11 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {Rockwell Extra} -size 15 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
vTcl:font:add_font \
    "-family {Rockwell Condensed} -size 40 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font18
vTcl:font:add_font \
    "-family {SI Font} -size 36 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#7a7a7a} 
    wm focusmodel $top passive
    wm geometry $top 935x638+237+119
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1596 873
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 10 -relief raised -background {#5b5b5b} -height 95 \
        -width 705 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -background {#5b5b5b} -disabledforeground {#a3a3a3} \
        -font {-family {SI Font} -size 36} -foreground {#ff2908} -text TAX 
    vTcl:DefineAlias "$site_3_0.lab44" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b5b5b} -disabledforeground {#a3a3a3} \
        -font {-family {SI Font} -size 36} -foreground {#2631d1} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text e 
    vTcl:DefineAlias "$site_3_0.lab45" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b5b5b} -disabledforeground {#a3a3a3} \
        -font {-family {SI Font} -size 36} -foreground {#fff71c} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 2019 
    vTcl:DefineAlias "$site_3_0.lab46" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b5b5b} -disabledforeground {#a3a3a3} \
        -font {-family {SI Font} -size 36} -foreground {#33a521} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -highlightthickness 0 -text {VIEW DATABASE} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 80 -y 10 -width 91 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 50 -y 10 -width 41 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 170 -y 10 -width 101 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 290 -y 10 -width 371 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra48 \
        -borderwidth 10 -relief sunken -background {#5b5b5b} -height 445 \
        -width 425 
    vTcl:DefineAlias "$top.fra48" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b5b5b} -disabledforeground {#a3a3a3} \
        -font {-family {SI Font} -size 36} -foreground {#432eff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Receipt 
    vTcl:DefineAlias "$site_3_0.lab51" "Label1_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -background {#5b5b5b} -disabledforeground {#a3a3a3} \
        -font {-family {Captain Howdy} -size 13} -foreground {#f7ff17} \
        -text {Get PDF copy of Reciept} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b5b5b} -disabledforeground {#a3a3a3} \
        -font {-family {Bodoni MT Black} -size 11 -weight bold} \
        -foreground {#f7ff17} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Enter UID Number Here :} 
    vTcl:DefineAlias "$site_3_0.lab57" "Label2_8" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent58 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent58" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but59 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#3f8e36} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Extra} -size 15 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text GENERATE 
    vTcl:DefineAlias "$site_3_0.but59" "btn_pdf" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join V:/ {edd project 2019 jan} {edd project modules} {advance option - view databases} adv1.png]] \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab65" "Label3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab51 \
        -in $site_3_0 -x 110 -y 20 -width 201 -relwidth 0 -height 48 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 90 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 40 -y 140 -width 344 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent58 \
        -in $site_3_0 -x 130 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 130 -y 230 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 150 -y 300 -width 104 -relwidth 0 -height 114 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra49 \
        -borderwidth 10 -relief sunken -background {#5b5b5b} -height 445 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 425 
    vTcl:DefineAlias "$top.fra49" "Frame2_4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra49
    label $site_3_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b5b5b} -disabledforeground {#a3a3a3} \
        -font {-family {SI Font} -size 36} -foreground {#432eff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Special List} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label1_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b5b5b} -disabledforeground {#a3a3a3} \
        -font {-family {Bodoni MT Black} -size 11 -weight bold} \
        -foreground {#f7ff17} -highlightbackground {#d9d9d9} \
        -highlightcolor black \
        -text {of people who paid less than 50% Ammount of tax} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label2_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b5b5b} -disabledforeground {#a3a3a3} \
        -font {-family {Captain Howdy} -size 13} -foreground {#f7ff17} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Get Excel sheet } 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2_8" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but60 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#3f8e36} -borderwidth 20 -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Condensed} -size 40 -weight bold} \
        -foreground {#111c7a} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {GET LIST} 
    vTcl:DefineAlias "$site_3_0.but60" "btn_getlist" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab66 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join V:/ {edd project 2019 jan} {edd project modules} {advance option - view databases} adv2.png]] \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab66" "Label4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab52 \
        -in $site_3_0 -x 100 -y 20 -width 241 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 20 -y 120 -width 384 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 70 -y 90 -width 284 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 90 -y 170 -width 265 -relwidth 0 -height 86 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 160 -y 280 -anchor nw -bordermode ignore 
    button $top.but67 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#ff2008} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Extra} -size 15 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text BACK 
    vTcl:DefineAlias "$top.but67" "btn_back" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 40 -y 30 -width 705 -relwidth 0 -height 95 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 30 -y 170 -width 425 -relwidth 0 -height 445 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 490 -y 170 -width 425 -relwidth 0 -height 445 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but67 \
        -in $top -x 790 -y 60 -width 95 -relwidth 0 -height 46 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

