#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Mar 08, 2019 11:19:06 PM IST  platform: Windows NT
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join F:/ {login page} login1.png]} {user image} user {}}
        {{[file join F:/ {login page} login2.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {MS UI Gothic} -size 14 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family Rockwell -size 17 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {Rockwell Extra Bold} -size 23 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
vTcl:font:add_font \
    "-family Rockwell -size 14 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m66" -background {#ffff30} 
    wm focusmodel $top passive
    wm geometry $top 763x561+439+167
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1604 882
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "loginpage" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#5b2af9} -height 365 \
        -width 525 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "loginpage" 1
    set site_3_0 $top.fra43
    entry $site_3_0.ent51 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent51" "Entry1" vTcl:WidgetProc "loginpage" 1
    entry $site_3_0.ent52 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent52" "Entry2" vTcl:WidgetProc "loginpage" 1
    label $site_3_0.lab54 \
        -background {#5b2af9} -disabledforeground {#5b2af9} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -text {Username :} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label1" vTcl:WidgetProc "loginpage" 1
    label $site_3_0.lab55 \
        -background {#5b2af9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -text {Password :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label2" vTcl:WidgetProc "loginpage" 1
    button $site_3_0.but61 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#3bfff8} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text LOGIN 
    vTcl:DefineAlias "$site_3_0.but61" "Button1" vTcl:WidgetProc "loginpage" 1
    button $site_3_0.but62 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#3bfff8} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text CANCEL 
    vTcl:DefineAlias "$site_3_0.but62" "Button1_1" vTcl:WidgetProc "loginpage" 1
    place $site_3_0.ent51 \
        -in $site_3_0 -x 200 -y 160 -width 214 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 200 -y 210 -width 214 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 70 -y 160 -width 114 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 70 -y 200 -anchor nw -bordermode ignore 
    place $site_3_0.but61 \
        -in $site_3_0 -x 320 -y 260 -width 87 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but62 \
        -in $site_3_0 -x 210 -y 260 -width 87 -height 24 -anchor nw \
        -bordermode ignore 
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background {#1fa53a} -height 365 \
        -width 465 
    vTcl:DefineAlias "$top.fra45" "Frame2" vTcl:WidgetProc "loginpage" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab65 \
        -background {#1fa53a} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#083a06} \
        -text {WELCOME } 
    vTcl:DefineAlias "$site_3_0.lab65" "Label3" vTcl:WidgetProc "loginpage" 1
    label $site_3_0.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#1fa53a} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font15,object) -foreground {#d12613} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {eTAX } 
    vTcl:DefineAlias "$site_3_0.lab67" "Label3_2" vTcl:WidgetProc "loginpage" 1
    label $site_3_0.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#1fa53a} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font15,object) -foreground {#2c18ad} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 2019 
    vTcl:DefineAlias "$site_3_0.lab68" "Label3_3" vTcl:WidgetProc "loginpage" 1
    label $site_3_0.lab69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#1fa53a} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#083a06} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text TO 
    vTcl:DefineAlias "$site_3_0.lab69" "Label3_4" vTcl:WidgetProc "loginpage" 1
    place $site_3_0.lab65 \
        -in $site_3_0 -x 40 -y 70 -width 154 -relwidth 0 -height 51 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 90 -y 170 -width 114 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 200 -y 170 -width 94 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 100 -y 120 -width 94 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background {#ff2d0d} -height 395 \
        -width 425 
    vTcl:DefineAlias "$top.fra47" "Frame3" vTcl:WidgetProc "loginpage" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab70 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join F:/ {login page} login1.png]] \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab70" "Label4" vTcl:WidgetProc "loginpage" 1
    place $site_3_0.lab70 \
        -in $site_3_0 -x 130 -y -10 -width 298 -relwidth 0 -height 182 \
        -relheight 0 -anchor nw -bordermode ignore 
    set site_3_0 $top.m66
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    label $top.lab71 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join F:/ {login page} login2.png]] \
        -text Label 
    vTcl:DefineAlias "$top.lab71" "Label5" vTcl:WidgetProc "loginpage" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 310 -y 210 -width 525 -relwidth 0 -height 365 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x -10 -y -30 -width 465 -relwidth 0 -height 365 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x -70 -y 280 -width 425 -relwidth 0 -height 395 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab71 \
        -in $top -x 560 -y 240 -width 104 -relwidth 0 -height 94 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

