#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Mar 08, 2019 11:19:04 PM IST  platform: Windows NT

'''

Copyright (c) 2019 Pranesh Kulkarni

'''

import sys
import tkinter
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import unknown_support
from tkinter import*

def main():                            # from here code of main software starts
        window=Tk()
        window.title("welcome")
        lbl=Label(window,text="hello")
        lbl.pack()


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = loginpage (root)
    unknown_support.init(root, top)
    root.mainloop()

w = None
def create_loginpage(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = loginpage (w)
    unknown_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_loginpage():
    global w
    w.destroy()
    w = None

class loginpage:
    def cancellogin(self):
        msg=tkinter.messagebox.askyesno("Login Page","Are You Sure , Do you Want to Cancel Login ?");         # Showing messagebox that asks user to cancel login
        if msg:
            exit()
    def loginuser(self):            
        name=self.Entry1.get();               # taking username input
        password=self.Entry2.get();           # taking password input
        if name == "a" and password == "a":   # checking username or password is correct or not
            tkinter.messagebox.showinfo("Login Page","The Login is Successful")                               # Showing messagebox that confirms login
            root.destroy()
            main()                                            # taking controll towards main application
        else:
            tkinter.messagebox.showwarning("Login Page","The username or password is incorrect");         # showing error
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {MS UI Gothic} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font11 = "-family Rockwell -size 17 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font15 = "-family {Rockwell Extra Bold} -size 23 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font9 = "-family Rockwell -size 14 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("763x561+439+167")
        top.title("New Toplevel")
        top.configure(background="#ffff30")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.406, rely=0.374, relheight=0.651
                , relwidth=0.688)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(background="#5b2af9")
        self.Frame1.configure(width=525)

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.381, rely=0.438,height=20, relwidth=0.408)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=214)

        self.Entry2 = tk.Entry(self.Frame1)
        self.Entry2.place(relx=0.381, rely=0.575,height=20, relwidth=0.408)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(width=214)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.133, rely=0.438, height=21, width=114)
        self.Label1.configure(background="#5b2af9")
        self.Label1.configure(disabledforeground="#5b2af9")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Username :''')
        self.Label1.configure(width=114)

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.133, rely=0.548, height=29, width=109)
        self.Label2.configure(background="#5b2af9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Password :''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.61, rely=0.712, height=24, width=87)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#3bfff8")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''LOGIN''')
        self.Button1.configure(width=87)
        self.Button1.configure(command=self.loginuser);             # Giving command to button1

        self.Button1_1 = tk.Button(self.Frame1)
        self.Button1_1.place(relx=0.4, rely=0.712, height=24, width=87)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#3bfff8")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font=font10)
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''CANCEL''')
        self.Button1_1.configure(command=self.cancellogin);         # Giving command to button1_1

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=-0.013, rely=-0.053, relheight=0.651
                , relwidth=0.609)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(background="#1fa53a")
        self.Frame2.configure(width=465)

        self.Label3 = tk.Label(self.Frame2)
        self.Label3.place(relx=0.086, rely=0.192, height=51, width=154)
        self.Label3.configure(background="#1fa53a")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font11)
        self.Label3.configure(foreground="#083a06")
        self.Label3.configure(text='''WELCOME''')
        self.Label3.configure(width=154)

        self.Label3_2 = tk.Label(self.Frame2)
        self.Label3_2.place(relx=0.194, rely=0.466, height=41, width=114)
        self.Label3_2.configure(activebackground="#f9f9f9")
        self.Label3_2.configure(activeforeground="black")
        self.Label3_2.configure(background="#1fa53a")
        self.Label3_2.configure(disabledforeground="#a3a3a3")
        self.Label3_2.configure(font=font15)
        self.Label3_2.configure(foreground="#d12613")
        self.Label3_2.configure(highlightbackground="#d9d9d9")
        self.Label3_2.configure(highlightcolor="black")
        self.Label3_2.configure(text='''eTAX''')
        self.Label3_2.configure(width=114)

        self.Label3_3 = tk.Label(self.Frame2)
        self.Label3_3.place(relx=0.43, rely=0.466, height=41, width=94)
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#1fa53a")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(font=font15)
        self.Label3_3.configure(foreground="#2c18ad")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''2019''')
        self.Label3_3.configure(width=94)

        self.Label3_4 = tk.Label(self.Frame2)
        self.Label3_4.place(relx=0.215, rely=0.329, height=31, width=94)
        self.Label3_4.configure(activebackground="#f9f9f9")
        self.Label3_4.configure(activeforeground="black")
        self.Label3_4.configure(background="#1fa53a")
        self.Label3_4.configure(disabledforeground="#a3a3a3")
        self.Label3_4.configure(font=font11)
        self.Label3_4.configure(foreground="#083a06")
        self.Label3_4.configure(highlightbackground="#d9d9d9")
        self.Label3_4.configure(highlightcolor="black")
        self.Label3_4.configure(text='''TO''')
        self.Label3_4.configure(width=94)

        self.Frame3 = tk.Frame(top)
        self.Frame3.place(relx=-0.092, rely=0.499, relheight=0.704
                , relwidth=0.557)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(background="#ff2d0d")
        self.Frame3.configure(width=425)

        self.Label4 = tk.Label(self.Frame3)
        self.Label4.place(relx=0.306, rely=-0.025, height=182, width=298)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self._img1 = tk.PhotoImage(file="./login1.png")
        self.Label4.configure(image=self._img1)
        self.Label4.configure(text='''Label''')
        self.Label4.configure(width=298)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.734, rely=0.428, height=94, width=104)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self._img2 = tk.PhotoImage(file="./login2.png")
        self.Label5.configure(image=self._img2)
        self.Label5.configure(text='''Label''')
        self.Label5.configure(width=104)

if __name__ == '__main__':
    vp_start_gui()





