#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Apr 25, 2019 02:51:08 PM +0530  platform: Windows NT

'''

Copyright (c) 2019 Pranesh Kulkarni

'''

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
import webbrowser
import tkinter
from tkinter import messagebox
import smtplib


try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import onlinesupport_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    print ('prog_call = {}'.format(prog_call))
    prog_location = os.path.split(prog_call)[0]
    print ('prog_location = {}'.format(prog_location))
    sys.stdout.flush()
    root = tk.Tk()
    onlinesupport_support.set_Tk_var()
    top = e_TAX_2019 (root)
    onlinesupport_support.init(root, top)
    root.mainloop()

w = None
def create_e_TAX_2019(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    global prog_location
    prog_call = sys.argv[0]
    print ('prog_call = {}'.format(prog_call))
    prog_location = os.path.split(prog_call)[0]
    print ('prog_location = {}'.format(prog_location))
    rt = root
    w = tk.Toplevel (root)
    onlinesupport_support.set_Tk_var()
    top = e_TAX_2019 (w)
    onlinesupport_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_e_TAX_2019():
    global w
    w.destroy()
    w = None

class e_TAX_2019:
    def facebooks(self):
        new =2
        url= "https://www.facebook.com/pranesh.kulkarni.359"
        webbrowser.open(url,new=new);

    def calls(self):
        new =2
        url= "https://api.whatsapp.com/send?phone=918956795667&text=Hi+User+here&fbclid=IwAR05YmoAuyw0dzyDMetLj3Zcya3QrJxfOW6sVmo4ydcqaaLf019RR4fNT0M"
        webbrowser.open(url,new=new);

    def websites(self):
        new =2
        url= "https://etax20194.webnode.com/"
        webbrowser.open(url,new=new);

    def submit2s(self):
        r1=str(self.spin1.get())
        r2=str(self.spin2.get())
        r3=str(self.spin3.get())
        r4=str(self.spin4.get())

        rev=str(self.txt_review.get())
        tot= r1+r2+r3+r4+rev
        mail= smtplib.SMTP('smtp.gmail.com',587)
        mail.ehlo()
        mail.starttls()
        mail.login('etaxsupp2019@gmail.com','Pass@123')
        mail.sendmail('etaxsupp2019@gmail.com','etaxsupp2019@gmail.com',tot)
        mail.close()
        messagebox.showinfo("e-TAX 2019","Thank You For Rating")


    def submit1s(self):
        a=str(self.txt_village.get())
        b=str(self.txt_username.get())
        c=str(self.txt_productid.get())
        d=str(self.txt_query.get())

        tota = a+b+c+d
        mail= smtplib.SMTP('smtp.gmail.com',587)
        mail.ehlo()
        mail.starttls()
        mail.login('etaxsupp2019@gmail.com','Pass@123')
        mail.sendmail('etaxsupp2019@gmail.com','etaxsupp2019@gmail.com',tota)
        mail.close()
        messagebox.showinfo("e-TAX 2019","Bug Reported.")

    def backs(self):
        root.destroy()
        print("wj")


    def exits(self):
        msg=tkinter.messagebox.askyesno("e-TAX 2019","Do You Want To EXIT ?")
        if msg:
            exit()





    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1162x780+138+34")
        top.title("e-TAX 2019")
        top.configure(background="#727272")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.164, rely=0.026, relheight=0.186
                , relwidth=0.667)
        self.Frame1.configure(relief='ridge')
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief='ridge')
        self.Frame1.configure(background="#595959")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=775)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.039, rely=0.207, height=59, width=196)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#595959")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Rockwell Extra} -size 40 -weight bold")
        self.Label1.configure(foreground="#0d4dff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''eTAX''')

        self.Label1_1 = tk.Label(self.Frame1)
        self.Label1_1.place(relx=0.271, rely=0.207, height=59, width=146)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#595959")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Rockwell Extra} -size 40 -weight bold")
        self.Label1_1.configure(foreground="#ff2b0a")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''2019''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.142, rely=0.621, height=31, width=184)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#595959")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Rage Italic} -size 19 -slant italic")
        self.Label2.configure(foreground="#f7ff0a")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''working for you''')

        self.Label1_2 = tk.Label(self.Frame1)
        self.Label1_2.place(relx=0.465, rely=0.207, height=69, width=356)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#595959")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font="-family {Rockwell Extra} -size 28 -weight bold")
        self.Label1_2.configure(foreground="#5faa14")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''Online Support''')

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.052, rely=0.256, relheight=0.455, relwidth=0.46)

        self.Frame2.configure(relief='ridge')
        self.Frame2.configure(borderwidth="10")
        self.Frame2.configure(relief='ridge')
        self.Frame2.configure(background="#595959")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")
        self.Frame2.configure(width=535)

        self.Label6 = tk.Label(self.Frame2)
        self.Label6.place(relx=0.224, rely=0.056, height=49, width=284)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#595959")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="-family {Franklin Gothic Demi Cond} -size 36")
        self.Label6.configure(foreground="#ff9e1f")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''REPORT A BUG''')

        self.Label6_5 = tk.Label(self.Frame2)
        self.Label6_5.place(relx=0.056, rely=0.254, height=39, width=94)
        self.Label6_5.configure(activebackground="#f9f9f9")
        self.Label6_5.configure(activeforeground="black")
        self.Label6_5.configure(background="#595959")
        self.Label6_5.configure(disabledforeground="#a3a3a3")
        self.Label6_5.configure(font="-family {Franklin Gothic Demi Cond} -size 16")
        self.Label6_5.configure(foreground="aqua")
        self.Label6_5.configure(highlightbackground="#d9d9d9")
        self.Label6_5.configure(highlightcolor="black")
        self.Label6_5.configure(text='''Village :''')

        self.Label6_6 = tk.Label(self.Frame2)
        self.Label6_6.place(relx=0.056, rely=0.366, height=39, width=94)
        self.Label6_6.configure(activebackground="#f9f9f9")
        self.Label6_6.configure(activeforeground="black")
        self.Label6_6.configure(background="#595959")
        self.Label6_6.configure(disabledforeground="#a3a3a3")
        self.Label6_6.configure(font="-family {Franklin Gothic Demi Cond} -size 16")
        self.Label6_6.configure(foreground="aqua")
        self.Label6_6.configure(highlightbackground="#d9d9d9")
        self.Label6_6.configure(highlightcolor="black")
        self.Label6_6.configure(text='''User Name :''')

        self.Label6_1 = tk.Label(self.Frame2)
        self.Label6_1.place(relx=0.056, rely=0.592, height=39, width=94)
        self.Label6_1.configure(activebackground="#f9f9f9")
        self.Label6_1.configure(activeforeground="black")
        self.Label6_1.configure(background="#595959")
        self.Label6_1.configure(disabledforeground="#a3a3a3")
        self.Label6_1.configure(font="-family {Franklin Gothic Demi Cond} -size 16")
        self.Label6_1.configure(foreground="aqua")
        self.Label6_1.configure(highlightbackground="#d9d9d9")
        self.Label6_1.configure(highlightcolor="black")
        self.Label6_1.configure(text='''Query :''')

        self.Label6_2 = tk.Label(self.Frame2)
        self.Label6_2.place(relx=0.056, rely=0.479, height=39, width=94)
        self.Label6_2.configure(activebackground="#f9f9f9")
        self.Label6_2.configure(activeforeground="black")
        self.Label6_2.configure(background="#595959")
        self.Label6_2.configure(disabledforeground="#a3a3a3")
        self.Label6_2.configure(font="-family {Franklin Gothic Demi Cond} -size 16")
        self.Label6_2.configure(foreground="aqua")
        self.Label6_2.configure(highlightbackground="#d9d9d9")
        self.Label6_2.configure(highlightcolor="black")
        self.Label6_2.configure(text='''Product ID :''')

        self.txt_village = tk.Entry(self.Frame2)
        self.txt_village.place(relx=0.28, rely=0.282,height=20, relwidth=0.643)
        self.txt_village.configure(background="white")
        self.txt_village.configure(disabledforeground="#a3a3a3")
        self.txt_village.configure(font="TkFixedFont")
        self.txt_village.configure(foreground="#000000")
        self.txt_village.configure(highlightbackground="#d9d9d9")
        self.txt_village.configure(highlightcolor="black")
        self.txt_village.configure(insertbackground="black")
        self.txt_village.configure(selectbackground="#c4c4c4")
        self.txt_village.configure(selectforeground="black")

        self.txt_username = tk.Entry(self.Frame2)
        self.txt_username.place(relx=0.28, rely=0.394, height=20, relwidth=0.643)

        self.txt_username.configure(background="white")
        self.txt_username.configure(disabledforeground="#a3a3a3")
        self.txt_username.configure(font="TkFixedFont")
        self.txt_username.configure(foreground="#000000")
        self.txt_username.configure(highlightbackground="#d9d9d9")
        self.txt_username.configure(highlightcolor="black")
        self.txt_username.configure(insertbackground="black")
        self.txt_username.configure(selectbackground="#c4c4c4")
        self.txt_username.configure(selectforeground="black")

        self.txt_productid = tk.Entry(self.Frame2)
        self.txt_productid.place(relx=0.28, rely=0.507, height=20
                , relwidth=0.643)
        self.txt_productid.configure(background="white")
        self.txt_productid.configure(disabledforeground="#a3a3a3")
        self.txt_productid.configure(font="TkFixedFont")
        self.txt_productid.configure(foreground="#000000")
        self.txt_productid.configure(highlightbackground="#d9d9d9")
        self.txt_productid.configure(highlightcolor="black")
        self.txt_productid.configure(insertbackground="black")
        self.txt_productid.configure(selectbackground="#c4c4c4")
        self.txt_productid.configure(selectforeground="black")

        self.txt_query = tk.Entry(self.Frame2)
        self.txt_query.place(relx=0.28, rely=0.62,height=70, relwidth=0.643)
        self.txt_query.configure(background="white")
        self.txt_query.configure(disabledforeground="#a3a3a3")
        self.txt_query.configure(font="TkFixedFont")
        self.txt_query.configure(foreground="#000000")
        self.txt_query.configure(highlightbackground="#d9d9d9")
        self.txt_query.configure(highlightcolor="black")
        self.txt_query.configure(insertbackground="black")
        self.txt_query.configure(selectbackground="#c4c4c4")
        self.txt_query.configure(selectforeground="black")

        self.btn_submit1 = tk.Button(self.Frame2)
        self.btn_submit1.place(relx=0.729, rely=0.845, height=34, width=80)
        self.btn_submit1.configure(activebackground="#ececec")
        self.btn_submit1.configure(activeforeground="#000000")
        self.btn_submit1.configure(background="#ff350d")
        self.btn_submit1.configure(borderwidth="10")
        self.btn_submit1.configure(disabledforeground="#a3a3a3")
        self.btn_submit1.configure(font="-family {Swatch it} -size 11 -weight bold")
        self.btn_submit1.configure(foreground="#000000")
        self.btn_submit1.configure(highlightbackground="#d9d9d9")
        self.btn_submit1.configure(highlightcolor="black")
        self.btn_submit1.configure(pady="0")
        self.btn_submit1.configure(text='''Submit''',command= self.submit1s)

        self.Frame2_1 = tk.Frame(top)
        self.Frame2_1.place(relx=0.525, rely=0.256, relheight=0.455
                , relwidth=0.443)
        self.Frame2_1.configure(relief='ridge')
        self.Frame2_1.configure(borderwidth="10")
        self.Frame2_1.configure(relief='ridge')
        self.Frame2_1.configure(background="#595959")
        self.Frame2_1.configure(highlightbackground="#d9d9d9")
        self.Frame2_1.configure(highlightcolor="black")
        self.Frame2_1.configure(width=515)

        self.Label6_11 = tk.Label(self.Frame2_1)
        self.Label6_11.place(relx=0.214, rely=0.028, height=49, width=284)
        self.Label6_11.configure(activebackground="#f9f9f9")
        self.Label6_11.configure(activeforeground="black")
        self.Label6_11.configure(background="#595959")
        self.Label6_11.configure(disabledforeground="#a3a3a3")
        self.Label6_11.configure(font="-family {Franklin Gothic Demi Cond} -size 36")
        self.Label6_11.configure(foreground="#ff9e1f")
        self.Label6_11.configure(highlightbackground="#d9d9d9")
        self.Label6_11.configure(highlightcolor="black")
        self.Label6_11.configure(text='''Give Rating''')

        self.Label6_3 = tk.Label(self.Frame2_1)
        self.Label6_3.place(relx=0.117, rely=0.225, height=39, width=94)
        self.Label6_3.configure(activebackground="#f9f9f9")
        self.Label6_3.configure(activeforeground="black")
        self.Label6_3.configure(background="#595959")
        self.Label6_3.configure(disabledforeground="#a3a3a3")
        self.Label6_3.configure(font="-family {Franklin Gothic Demi Cond} -size 16")
        self.Label6_3.configure(foreground="aqua")
        self.Label6_3.configure(highlightbackground="#d9d9d9")
        self.Label6_3.configure(highlightcolor="black")
        self.Label6_3.configure(text='''UI :''')

        self.Label6_7 = tk.Label(self.Frame2_1)
        self.Label6_7.place(relx=0.058, rely=0.31, height=39, width=174)
        self.Label6_7.configure(activebackground="#f9f9f9")
        self.Label6_7.configure(activeforeground="black")
        self.Label6_7.configure(background="#595959")
        self.Label6_7.configure(disabledforeground="#a3a3a3")
        self.Label6_7.configure(font="-family {Franklin Gothic Demi Cond} -size 16")
        self.Label6_7.configure(foreground="aqua")
        self.Label6_7.configure(highlightbackground="#d9d9d9")
        self.Label6_7.configure(highlightcolor="black")
        self.Label6_7.configure(text='''Server Connectivity :''')

        self.Label6_4 = tk.Label(self.Frame2_1)
        self.Label6_4.place(relx=0.019, rely=0.394, height=39, width=204)
        self.Label6_4.configure(activebackground="#f9f9f9")
        self.Label6_4.configure(activeforeground="black")
        self.Label6_4.configure(background="#595959")
        self.Label6_4.configure(disabledforeground="#a3a3a3")
        self.Label6_4.configure(font="-family {Franklin Gothic Demi Cond} -size 16")
        self.Label6_4.configure(foreground="aqua")
        self.Label6_4.configure(highlightbackground="#d9d9d9")
        self.Label6_4.configure(highlightcolor="black")
        self.Label6_4.configure(text='''Costomer Care Service :''')

        self.Label6_5 = tk.Label(self.Frame2_1)
        self.Label6_5.place(relx=0.058, rely=0.479, height=39, width=154)
        self.Label6_5.configure(activebackground="#f9f9f9")
        self.Label6_5.configure(activeforeground="black")
        self.Label6_5.configure(background="#595959")
        self.Label6_5.configure(disabledforeground="#a3a3a3")
        self.Label6_5.configure(font="-family {Franklin Gothic Demi Cond} -size 16")
        self.Label6_5.configure(foreground="aqua")
        self.Label6_5.configure(highlightbackground="#d9d9d9")
        self.Label6_5.configure(highlightcolor="black")
        self.Label6_5.configure(text='''Overall Ratings:''')

        self.spin1 = tk.Spinbox(self.Frame2_1, from_=1.0, to=5.0)
        self.spin1.place(relx=0.544, rely=0.254, relheight=0.054, relwidth=0.146)

        self.spin1.configure(activebackground="#f9f9f9")
        self.spin1.configure(background="white")
        self.spin1.configure(buttonbackground="#a3a5a8")
        self.spin1.configure(disabledforeground="#a3a3a3")
        self.spin1.configure(foreground="black")
        self.spin1.configure(highlightbackground="black")
        self.spin1.configure(highlightcolor="black")
        self.spin1.configure(insertbackground="black")
        self.spin1.configure(selectbackground="#c4c4c4")
        self.spin1.configure(selectforeground="black")
        self.spin1.configure(textvariable=onlinesupport_support.spinbox1)

        self.Label5_4 = tk.Label(self.Frame2_1)
        self.Label5_4.place(relx=0.35, rely=0.169, height=22, width=152)
        self.Label5_4.configure(activebackground="#f9f9f9")
        self.Label5_4.configure(activeforeground="black")
        self.Label5_4.configure(background="#595959")
        self.Label5_4.configure(disabledforeground="#a3a3a3")
        self.Label5_4.configure(font="-family {Rockwell} -size 11 -slant italic")
        self.Label5_4.configure(foreground="#f7ff14")
        self.Label5_4.configure(highlightbackground="#d9d9d9")
        self.Label5_4.configure(highlightcolor="black")
        self.Label5_4.configure(text='''Give Out of 5''')

        self.spin4 = tk.Spinbox(self.Frame2_1, from_=1.0, to=5.0)
        self.spin4.place(relx=0.544, rely=0.507, relheight=0.054, relwidth=0.146)

        self.spin4.configure(activebackground="#f9f9f9")
        self.spin4.configure(background="white")
        self.spin4.configure(buttonbackground="#a3a5a8")
        self.spin4.configure(disabledforeground="#a3a3a3")
        self.spin4.configure(foreground="black")
        self.spin4.configure(highlightbackground="black")
        self.spin4.configure(highlightcolor="black")
        self.spin4.configure(insertbackground="black")
        self.spin4.configure(selectbackground="#c4c4c4")
        self.spin4.configure(selectforeground="black")
        self.spin4.configure(textvariable=onlinesupport_support.spinbox4)

        self.spin3 = tk.Spinbox(self.Frame2_1, from_=1.0, to=5.0)
        self.spin3.place(relx=0.544, rely=0.423, relheight=0.054, relwidth=0.146)

        self.spin3.configure(activebackground="#f9f9f9")
        self.spin3.configure(background="white")
        self.spin3.configure(buttonbackground="#a3a5a8")
        self.spin3.configure(disabledforeground="#a3a3a3")
        self.spin3.configure(foreground="black")
        self.spin3.configure(highlightbackground="black")
        self.spin3.configure(highlightcolor="black")
        self.spin3.configure(insertbackground="black")
        self.spin3.configure(selectbackground="#c4c4c4")
        self.spin3.configure(selectforeground="black")
        self.spin3.configure(textvariable=onlinesupport_support.spinbox3)

        self.spin2 = tk.Spinbox(self.Frame2_1, from_=1.0, to=5.0)
        self.spin2.place(relx=0.544, rely=0.338, relheight=0.054, relwidth=0.146)

        self.spin2.configure(activebackground="#f9f9f9")
        self.spin2.configure(background="white")
        self.spin2.configure(buttonbackground="#a3a5a8")
        self.spin2.configure(disabledforeground="#a3a3a3")
        self.spin2.configure(foreground="black")
        self.spin2.configure(highlightbackground="black")
        self.spin2.configure(highlightcolor="black")
        self.spin2.configure(insertbackground="black")
        self.spin2.configure(selectbackground="#c4c4c4")
        self.spin2.configure(selectforeground="black")
        self.spin2.configure(textvariable=onlinesupport_support.spinbox2)

        self.Label6_9 = tk.Label(self.Frame2_1)
        self.Label6_9.place(relx=0.252, rely=0.592, height=49, width=284)
        self.Label6_9.configure(activebackground="#f9f9f9")
        self.Label6_9.configure(activeforeground="black")
        self.Label6_9.configure(background="#595959")
        self.Label6_9.configure(disabledforeground="#a3a3a3")
        self.Label6_9.configure(font="-family {Franklin Gothic Demi Cond} -size 36")
        self.Label6_9.configure(foreground="#ff9e1f")
        self.Label6_9.configure(highlightbackground="#d9d9d9")
        self.Label6_9.configure(highlightcolor="black")
        self.Label6_9.configure(text='''Write A Review''')

        self.txt_review = tk.Entry(self.Frame2_1)
        self.txt_review.place(relx=0.078, rely=0.732,height=30, relwidth=0.804)
        self.txt_review.configure(background="white")
        self.txt_review.configure(disabledforeground="#a3a3a3")
        self.txt_review.configure(font="TkFixedFont")
        self.txt_review.configure(foreground="#000000")
        self.txt_review.configure(highlightbackground="#d9d9d9")
        self.txt_review.configure(highlightcolor="black")
        self.txt_review.configure(insertbackground="black")
        self.txt_review.configure(selectbackground="#c4c4c4")
        self.txt_review.configure(selectforeground="black")

        self.btn_submit2 = tk.Button(self.Frame2_1)
        self.btn_submit2.place(relx=0.408, rely=0.845, height=34, width=80)
        self.btn_submit2.configure(activebackground="#ececec")
        self.btn_submit2.configure(activeforeground="#000000")
        self.btn_submit2.configure(background="#ff350d")
        self.btn_submit2.configure(borderwidth="10")
        self.btn_submit2.configure(disabledforeground="#a3a3a3")
        self.btn_submit2.configure(font="-family {Swatch it} -size 11 -weight bold")
        self.btn_submit2.configure(foreground="#000000")
        self.btn_submit2.configure(highlightbackground="#d9d9d9")
        self.btn_submit2.configure(highlightcolor="black")
        self.btn_submit2.configure(pady="0")
        self.btn_submit2.configure(text='''Submit''',command= self.submit2s)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.034, rely=0.731, height=176, width=304)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"./online2.png")
        self._img0 = tk.PhotoImage(file=photo_location)
        self.Label3.configure(image=self._img0)
        self.Label3.configure(text='''Label''')

        self.Frame2_2 = tk.Frame(top)
        self.Frame2_2.place(relx=0.336, rely=0.731, relheight=0.224
                , relwidth=0.331)
        self.Frame2_2.configure(relief='ridge')
        self.Frame2_2.configure(borderwidth="10")
        self.Frame2_2.configure(relief='ridge')
        self.Frame2_2.configure(background="#595959")
        self.Frame2_2.configure(highlightbackground="#d9d9d9")
        self.Frame2_2.configure(highlightcolor="black")
        self.Frame2_2.configure(width=385)

        self.Label4 = tk.Label(self.Frame2_2)
        self.Label4.place(relx=0.39, rely=0.114, height=23, width=99)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#595959")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {SF Distant Galaxy} -size 13")
        self.Label4.configure(foreground="#ffff12")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Contact''')

        self.btn_facebook = tk.Button(self.Frame2_2)
        self.btn_facebook.place(relx=0.104, rely=0.343, height=91, width=96)
        self.btn_facebook.configure(activebackground="#ececec")
        self.btn_facebook.configure(activeforeground="#000000")
        self.btn_facebook.configure(background="#d9d9d9")
        self.btn_facebook.configure(borderwidth="10")
        self.btn_facebook.configure(disabledforeground="#a3a3a3")
        self.btn_facebook.configure(foreground="#000000")
        self.btn_facebook.configure(highlightbackground="#d9d9d9")
        self.btn_facebook.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"./facebook-logo-png-5a35528eaa4f08.7998622015134439826976.png")
        self._img1 = tk.PhotoImage(file=photo_location)
        self.btn_facebook.configure(image=self._img1)
        self.btn_facebook.configure(overrelief="raised")
        self.btn_facebook.configure(pady="0")
        self.btn_facebook.configure(text='''Button''',command= self.facebooks)

        self.btn_website = tk.Button(self.Frame2_2)
        self.btn_website.place(relx=0.416, rely=0.343, height=86, width=86)
        self.btn_website.configure(activebackground="#ececec")
        self.btn_website.configure(activeforeground="#000000")
        self.btn_website.configure(background="#d9d9d9")
        self.btn_website.configure(borderwidth="10")
        self.btn_website.configure(disabledforeground="#a3a3a3")
        self.btn_website.configure(foreground="#000000")
        self.btn_website.configure(highlightbackground="#d9d9d9")
        self.btn_website.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"./icon_weebly.com_bot_02e090.png")
        self._img2 = tk.PhotoImage(file=photo_location)
        self.btn_website.configure(image=self._img2)
        self.btn_website.configure(pady="0")
        self.btn_website.configure(text='''Button''',command= self.websites)

        self.btn_call = tk.Button(self.Frame2_2)
        self.btn_call.place(relx=0.701, rely=0.343, height=92, width=91)
        self.btn_call.configure(activebackground="#ececec")
        self.btn_call.configure(activeforeground="#000000")
        self.btn_call.configure(background="#d9d9d9")
        self.btn_call.configure(borderwidth="10")
        self.btn_call.configure(disabledforeground="#a3a3a3")
        self.btn_call.configure(foreground="#000000")
        self.btn_call.configure(highlightbackground="#d9d9d9")
        self.btn_call.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"./2019-04-25 14_03_03-Downloads.png")
        self._img3 = tk.PhotoImage(file=photo_location)
        self.btn_call.configure(image=self._img3)
        self.btn_call.configure(pady="0")
        self.btn_call.configure(text='''Button''',command= self.calls)

        self.Frame2_3 = tk.Frame(top)
        self.Frame2_3.place(relx=0.68, rely=0.731, relheight=0.25
                , relwidth=0.297)
        self.Frame2_3.configure(relief='ridge')
        self.Frame2_3.configure(borderwidth="10")
        self.Frame2_3.configure(relief='ridge')
        self.Frame2_3.configure(background="#595959")
        self.Frame2_3.configure(highlightbackground="#d9d9d9")
        self.Frame2_3.configure(highlightcolor="black")
        self.Frame2_3.configure(width=345)

        self.Label5 = tk.Label(self.Frame2_3)
        self.Label5.place(relx=0.232, rely=0.051, height=32, width=172)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#595959")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="-family {Rockwell} -size 17 -slant italic")
        self.Label5.configure(foreground="#1fff0f")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''::: Developers :::''')

        self.Label5_3 = tk.Label(self.Frame2_3)
        self.Label5_3.place(relx=0.261, rely=0.205, height=32, width=152)
        self.Label5_3.configure(activebackground="#f9f9f9")
        self.Label5_3.configure(activeforeground="black")
        self.Label5_3.configure(background="#595959")
        self.Label5_3.configure(disabledforeground="#a3a3a3")
        self.Label5_3.configure(font="-family {Rockwell} -size 11 -slant italic")
        self.Label5_3.configure(foreground="aqua")
        self.Label5_3.configure(highlightbackground="#d9d9d9")
        self.Label5_3.configure(highlightcolor="black")
        self.Label5_3.configure(text='''Pranesh Kulkarni''')

        self.Label5_5 = tk.Label(self.Frame2_3)
        self.Label5_5.place(relx=0.261, rely=0.564, height=22, width=152)
        self.Label5_5.configure(activebackground="#f9f9f9")
        self.Label5_5.configure(activeforeground="black")
        self.Label5_5.configure(background="#595959")
        self.Label5_5.configure(disabledforeground="#a3a3a3")
        self.Label5_5.configure(font="-family {Rockwell} -size 11 -slant italic")
        self.Label5_5.configure(foreground="aqua")
        self.Label5_5.configure(highlightbackground="#d9d9d9")
        self.Label5_5.configure(highlightcolor="black")
        self.Label5_5.configure(text='''Prathamesh Dhasade''')

        self.Label5_5 = tk.Label(self.Frame2_3)
        self.Label5_5.place(relx=0.261, rely=0.667, height=22, width=152)
        self.Label5_5.configure(activebackground="#f9f9f9")
        self.Label5_5.configure(activeforeground="black")
        self.Label5_5.configure(background="#595959")
        self.Label5_5.configure(disabledforeground="#a3a3a3")
        self.Label5_5.configure(font="-family {Rockwell} -size 11 -slant italic")
        self.Label5_5.configure(foreground="aqua")
        self.Label5_5.configure(highlightbackground="#d9d9d9")
        self.Label5_5.configure(highlightcolor="black")
        self.Label5_5.configure(text='''Anjali Gayakwad''')

        self.Label5_5 = tk.Label(self.Frame2_3)
        self.Label5_5.place(relx=0.261, rely=0.769, height=32, width=152)
        self.Label5_5.configure(activebackground="#f9f9f9")
        self.Label5_5.configure(activeforeground="black")
        self.Label5_5.configure(background="#595959")
        self.Label5_5.configure(disabledforeground="#a3a3a3")
        self.Label5_5.configure(font="-family {Rockwell} -size 11 -slant italic")
        self.Label5_5.configure(foreground="aqua")
        self.Label5_5.configure(highlightbackground="#d9d9d9")
        self.Label5_5.configure(highlightcolor="black")
        self.Label5_5.configure(text='''Shraddha Kshirsagar''')

        self.Label5_5 = tk.Label(self.Frame2_3)
        self.Label5_5.place(relx=0.261, rely=0.462, height=22, width=152)
        self.Label5_5.configure(activebackground="#f9f9f9")
        self.Label5_5.configure(activeforeground="black")
        self.Label5_5.configure(background="#595959")
        self.Label5_5.configure(disabledforeground="#a3a3a3")
        self.Label5_5.configure(font="-family {Rockwell} -size 11 -slant italic")
        self.Label5_5.configure(foreground="aqua")
        self.Label5_5.configure(highlightbackground="#d9d9d9")
        self.Label5_5.configure(highlightcolor="black")
        self.Label5_5.configure(text='''Ankita Chirame''')

        self.Label5_5 = tk.Label(self.Frame2_3)
        self.Label5_5.place(relx=0.261, rely=0.359, height=22, width=152)
        self.Label5_5.configure(activebackground="#f9f9f9")
        self.Label5_5.configure(activeforeground="black")
        self.Label5_5.configure(background="#595959")
        self.Label5_5.configure(disabledforeground="#a3a3a3")
        self.Label5_5.configure(font="-family {Rockwell} -size 11 -slant italic")
        self.Label5_5.configure(foreground="aqua")
        self.Label5_5.configure(highlightbackground="#d9d9d9")
        self.Label5_5.configure(highlightcolor="black")
        self.Label5_5.configure(text='''Anamika Rathod''')

        self.btn_submit2_11 = tk.Button(top)
        self.btn_submit2_11.place(relx=0.869, rely=0.115, height=44, width=90)
        self.btn_submit2_11.configure(activebackground="#ececec")
        self.btn_submit2_11.configure(activeforeground="#000000")
        self.btn_submit2_11.configure(background="#3045ff")
        self.btn_submit2_11.configure(borderwidth="10")
        self.btn_submit2_11.configure(disabledforeground="#a3a3a3")
        self.btn_submit2_11.configure(font="-family {Swatch it} -size 11 -weight bold")
        self.btn_submit2_11.configure(foreground="#000000")
        self.btn_submit2_11.configure(highlightbackground="#d9d9d9")
        self.btn_submit2_11.configure(highlightcolor="black",command= self.exits)
        self.btn_submit2_11.configure(pady="0")
        self.btn_submit2_11.configure(text='''Exit''')

        self.btn_back = tk.Button(top)
        self.btn_back.place(relx=0.869, rely=0.051, height=44, width=90)
        self.btn_back.configure(activebackground="#ececec")
        self.btn_back.configure(activeforeground="#000000")
        self.btn_back.configure(background="#2ba30d")
        self.btn_back.configure(borderwidth="10")
        self.btn_back.configure(disabledforeground="#a3a3a3")
        self.btn_back.configure(font="-family {Swatch it} -size 11 -weight bold")
        self.btn_back.configure(foreground="#000000")
        self.btn_back.configure(highlightbackground="#d9d9d9")
        self.btn_back.configure(highlightcolor="black")
        self.btn_back.configure(pady="0")
        self.btn_back.configure(text='''Back''',command = self.backs)

if __name__ == '__main__':
    vp_start_gui()





