#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Apr 22, 2019 03:51:06 PM +0530  platform: Windows NT

'''

Copyright (c) 2019 Pranesh Kulkarni

'''

import sys
import tkinter
import time
from tkinter import messagebox
import smtplib

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import permit_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = e_TAX_2019 (root)
    permit_support.init(root, top)
    root.mainloop()

w = None
def create_e_TAX_2019(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = e_TAX_2019 (w)
    permit_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_e_TAX_2019():
    global w
    w.destroy()
    w = None

class e_TAX_2019:
    def exits(self):
        msg=tkinter.messagebox.showinfo("e-TAX 2019","Do You Want To EXIT ?")
        if msg :
            exit()
    def backs(self):
        root.destroy()
        print("nwhcwjjwdj")

    def submits(self):
        p=str(self.txt_productkey.get());
        v=str(self.txt_village.get());
        u=str(self.txt_username.get());
        n=str(self.txt_noofentries.get());
        r=str(self.txt_reason.get());
        t=str(time.asctime(time.localtime(time.time())))


        totcontaint = str("Hi there is a new request for updating e-TAX 2019 database \n\n\n here are DETAILS ::::::\n\n\nproduct key :"+p+"\n village name :"+v+"\n Username :"+u+"\n No. of entries to modify :"+n+"\n Reason to modify data :"+r+"\n\n\n\n\n Requested on :"+t)
        mail= smtplib.SMTP('smtp.gmail.com',587)
        mail.ehlo()
        mail.starttls()
        mail.login('etaxsupp2019@gmail.com','Pass@123')
        mail.sendmail('etaxsupp2019@gmail.com','kulkarnipranesh1767@gmail.com',totcontaint)
        mail.close()
        messagebox.showinfo("e-TAX 2019","Requested for updating Data. Wait for Confirmation from Administrator. After recieving Confirmation Email From Administrator You can modify database through respective modules")
        root.destroy()



    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font12 = "-family {GoudyHandtooled BT} -size 22"
        font15 = "-family {System} -size 10 -weight bold"
        font16 = "-family {Segoe UI} -size 12"

        top.geometry("990x650+273+127")
        top.title("e-TAX 2019")
        top.configure(background="#727272")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.141, rely=0.046, relheight=0.223
                , relwidth=0.712)
        self.Frame1.configure(relief='ridge')
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief='ridge')
        self.Frame1.configure(background="#595959")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=705)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.043, rely=0.207, height=59, width=196)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#595959")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Rockwell Extra} -size 40 -weight bold")
        self.Label1.configure(foreground="#0d4dff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''eTAX''')

        self.Label1_1 = tk.Label(self.Frame1)
        self.Label1_1.place(relx=0.298, rely=0.207, height=59, width=146)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#595959")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Rockwell Extra} -size 40 -weight bold")
        self.Label1_1.configure(foreground="#ff2b0a")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''2019''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.156, rely=0.621, height=31, width=184)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#595959")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Rage Italic} -size 19 -slant italic")
        self.Label2.configure(foreground="#f7ff0a")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''working for you''')

        self.Label1_2 = tk.Label(self.Frame1)
        self.Label1_2.place(relx=0.525, rely=0.207, height=79, width=306)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#595959")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font="-family {Rockwell Extra} -size 28 -weight bold")
        self.Label1_2.configure(foreground="#5faa14")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''PERMISSION''')
        self.Label1_2.configure(width=306)

        self.Frame1_1 = tk.Frame(top)
        self.Frame1_1.place(relx=0.141, rely=0.308, relheight=0.577
                , relwidth=0.712)
        self.Frame1_1.configure(relief='ridge')
        self.Frame1_1.configure(borderwidth="10")
        self.Frame1_1.configure(relief='ridge')
        self.Frame1_1.configure(background="#595959")
        self.Frame1_1.configure(highlightbackground="#d9d9d9")
        self.Frame1_1.configure(highlightcolor="black")
        self.Frame1_1.configure(width=705)

        self.Label3 = tk.Label(self.Frame1_1)
        self.Label3.place(relx=0.156, rely=0.08, height=41, width=446)
        self.Label3.configure(background="#595959")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font12)
        self.Label3.configure(foreground="#fbf2ff")
        self.Label3.configure(text='''FILL YOUR PRODUCT DETAILS''')

        self.Label4 = tk.Label(self.Frame1_1)
        self.Label4.place(relx=0.142, rely=0.24, height=22, width=102)
        self.Label4.configure(background="#595959")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font15)
        self.Label4.configure(foreground="AQUA")
        self.Label4.configure(text='''Product Key :''')
        self.Label4.configure(width=102)

        self.Label4_5 = tk.Label(self.Frame1_1)
        self.Label4_5.place(relx=0.142, rely=0.32, height=22, width=102)
        self.Label4_5.configure(activebackground="#f9f9f9")
        self.Label4_5.configure(activeforeground="black")
        self.Label4_5.configure(background="#595959")
        self.Label4_5.configure(disabledforeground="#a3a3a3")
        self.Label4_5.configure(font="-family {System} -size 10 -weight bold")
        self.Label4_5.configure(foreground="AQUA")
        self.Label4_5.configure(highlightbackground="#d9d9d9")
        self.Label4_5.configure(highlightcolor="black")
        self.Label4_5.configure(text='''Village :''')

        self.Label4_6 = tk.Label(self.Frame1_1)
        self.Label4_6.place(relx=0.142, rely=0.4, height=22, width=102)
        self.Label4_6.configure(activebackground="#f9f9f9")
        self.Label4_6.configure(activeforeground="black")
        self.Label4_6.configure(background="#595959")
        self.Label4_6.configure(disabledforeground="#a3a3a3")
        self.Label4_6.configure(font="-family {System} -size 10 -weight bold")
        self.Label4_6.configure(foreground="AQUA")
        self.Label4_6.configure(highlightbackground="#d9d9d9")
        self.Label4_6.configure(highlightcolor="black")
        self.Label4_6.configure(text='''Username :''')

        self.Label4_7 = tk.Label(self.Frame1_1)
        self.Label4_7.place(relx=0.085, rely=0.48, height=22, width=202)
        self.Label4_7.configure(activebackground="#f9f9f9")
        self.Label4_7.configure(activeforeground="black")
        self.Label4_7.configure(background="#595959")
        self.Label4_7.configure(disabledforeground="#a3a3a3")
        self.Label4_7.configure(font="-family {System} -size 10 -weight bold")
        self.Label4_7.configure(foreground="AQUA")
        self.Label4_7.configure(highlightbackground="#d9d9d9")
        self.Label4_7.configure(highlightcolor="black")
        self.Label4_7.configure(text='''No. of entries to update :''')
        self.Label4_7.configure(width=202)

        self.Label4_8 = tk.Label(self.Frame1_1)
        self.Label4_8.place(relx=0.099, rely=0.56, height=22, width=172)
        self.Label4_8.configure(activebackground="#f9f9f9")
        self.Label4_8.configure(activeforeground="black")
        self.Label4_8.configure(background="#595959")
        self.Label4_8.configure(disabledforeground="#a3a3a3")
        self.Label4_8.configure(font="-family {System} -size 10 -weight bold")
        self.Label4_8.configure(foreground="AQUA")
        self.Label4_8.configure(highlightbackground="#d9d9d9")
        self.Label4_8.configure(highlightcolor="black")
        self.Label4_8.configure(text='''Reason to modify data :''')
        self.Label4_8.configure(width=172)

        self.txt_productkey = tk.Entry(self.Frame1_1)
        self.txt_productkey.place(relx=0.397, rely=0.24, height=20
                , relwidth=0.445)
        self.txt_productkey.configure(background="white")
        self.txt_productkey.configure(disabledforeground="#a3a3a3")
        self.txt_productkey.configure(font="TkFixedFont")
        self.txt_productkey.configure(foreground="#000000")
        self.txt_productkey.configure(insertbackground="black")
        self.txt_productkey.configure(width=314)

        self.txt_reason = tk.Entry(self.Frame1_1)
        self.txt_reason.place(relx=0.397, rely=0.56,height=20, relwidth=0.445)
        self.txt_reason.configure(background="white")
        self.txt_reason.configure(disabledforeground="#a3a3a3")
        self.txt_reason.configure(font="TkFixedFont")
        self.txt_reason.configure(foreground="#000000")
        self.txt_reason.configure(highlightbackground="#d9d9d9")
        self.txt_reason.configure(highlightcolor="black")
        self.txt_reason.configure(insertbackground="black")
        self.txt_reason.configure(selectbackground="#c4c4c4")
        self.txt_reason.configure(selectforeground="black")

        self.txt_noofentries = tk.Entry(self.Frame1_1)
        self.txt_noofentries.place(relx=0.397, rely=0.48, height=20
                , relwidth=0.445)
        self.txt_noofentries.configure(background="white")
        self.txt_noofentries.configure(disabledforeground="#a3a3a3")
        self.txt_noofentries.configure(font="TkFixedFont")
        self.txt_noofentries.configure(foreground="#000000")
        self.txt_noofentries.configure(highlightbackground="#d9d9d9")
        self.txt_noofentries.configure(highlightcolor="black")
        self.txt_noofentries.configure(insertbackground="black")
        self.txt_noofentries.configure(selectbackground="#c4c4c4")
        self.txt_noofentries.configure(selectforeground="black")

        self.txt_username = tk.Entry(self.Frame1_1)
        self.txt_username.place(relx=0.397, rely=0.4,height=20, relwidth=0.445)
        self.txt_username.configure(background="white")
        self.txt_username.configure(disabledforeground="#a3a3a3")
        self.txt_username.configure(font="TkFixedFont")
        self.txt_username.configure(foreground="#000000")
        self.txt_username.configure(highlightbackground="#d9d9d9")
        self.txt_username.configure(highlightcolor="black")
        self.txt_username.configure(insertbackground="black")
        self.txt_username.configure(selectbackground="#c4c4c4")
        self.txt_username.configure(selectforeground="black")

        self.txt_village = tk.Entry(self.Frame1_1)
        self.txt_village.place(relx=0.397, rely=0.32,height=20, relwidth=0.445)
        self.txt_village.configure(background="white")
        self.txt_village.configure(disabledforeground="#a3a3a3")
        self.txt_village.configure(font="TkFixedFont")
        self.txt_village.configure(foreground="#000000")
        self.txt_village.configure(highlightbackground="#d9d9d9")
        self.txt_village.configure(highlightcolor="black")
        self.txt_village.configure(insertbackground="black")
        self.txt_village.configure(selectbackground="#c4c4c4")
        self.txt_village.configure(selectforeground="black")

        self.btn_submit = tk.Button(self.Frame1_1)
        self.btn_submit.place(relx=0.454, rely=0.667, height=44, width=227)
        self.btn_submit.configure(activebackground="#ececec")
        self.btn_submit.configure(activeforeground="#000000")
        self.btn_submit.configure(background="#3028a0")
        self.btn_submit.configure(borderwidth="10")
        self.btn_submit.configure(disabledforeground="#a3a3a3")
        self.btn_submit.configure(font=font16)
        self.btn_submit.configure(foreground="#ffffff")
        self.btn_submit.configure(highlightbackground="#d9d9d9")
        self.btn_submit.configure(highlightcolor="black")
        self.btn_submit.configure(pady="0")
        self.btn_submit.configure(text='''Ask for permission''',command = self.submits)
        self.btn_submit.configure(width=227)

        self.btn_exit = tk.Button(top)
        self.btn_exit.place(relx=0.879, rely=0.169, height=44, width=107)
        self.btn_exit.configure(activebackground="#ececec")
        self.btn_exit.configure(activeforeground="#000000")
        self.btn_exit.configure(background="#ff002b")
        self.btn_exit.configure(borderwidth="10")
        self.btn_exit.configure(disabledforeground="#a3a3a3")
        self.btn_exit.configure(font="-family {Segoe UI} -size 12")
        self.btn_exit.configure(foreground="#ffffff")
        self.btn_exit.configure(highlightbackground="#d9d9d9")
        self.btn_exit.configure(highlightcolor="black")
        self.btn_exit.configure(pady="0")
        self.btn_exit.configure(text='''EXIT''',command = self.exits)
        self.btn_exit.configure(width=107)

        self.btn_back = tk.Button(top)
        self.btn_back.place(relx=0.879, rely=0.077, height=44, width=107)
        self.btn_back.configure(activebackground="#ececec")
        self.btn_back.configure(activeforeground="#000000")
        self.btn_back.configure(background="#39a324")
        self.btn_back.configure(borderwidth="10")
        self.btn_back.configure(disabledforeground="#a3a3a3")
        self.btn_back.configure(font="-family {Segoe UI} -size 12")
        self.btn_back.configure(foreground="#ffffff")
        self.btn_back.configure(highlightbackground="#d9d9d9")
        self.btn_back.configure(highlightcolor="black")
        self.btn_back.configure(pady="0")
        self.btn_back.configure(text='''BACK''',command = self.backs)

if __name__ == '__main__':
    vp_start_gui()





