#############################################################################
# Generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#  Apr 21, 2019 05:48:50 PM +0530  platform: Windows NT
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra mainpage bg1.png]} {user image} user {}}
        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra mainpage bg2.png]} {user image} user {}}
        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra mainpage bg3.png]} {user image} user {}}
        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra mainpage bg4.png]} {user image} user {}}
        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra mainpage login3.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Harlow Solid Italic} -size 40 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {BadBlocks TT} -size 28 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {BadBlocks TT} -size 24 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {Serifa BT} -size 14 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font14
vTcl:font:add_font \
    "-family {Sky Skunk} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
vTcl:font:add_font \
    "-family {BankGothic Md BT} -size 40 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background {#939393} 
    wm focusmodel $top passive
    wm geometry $top 992x628+286+152
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1596 873
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "eTAX- 2019"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m43
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    frame $top.fra44 \
        -borderwidth 10 -relief ridge -background {#595959} -height 85 \
        -width 635 
    vTcl:DefineAlias "$top.fra44" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra44
    label $site_3_0.lab49 \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {BankGothic Md BT} -size 40 -weight bold} \
        -foreground {#ff2a00} -text e-TAX 
    vTcl:DefineAlias "$site_3_0.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {BankGothic Md BT} -size 40 -weight bold} \
        -foreground {#143bff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 2019 
    vTcl:DefineAlias "$site_3_0.lab50" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Harlow Solid Italic} -size 40 -slant italic} \
        -foreground {#f0ff1c} -text extra 
    vTcl:DefineAlias "$site_3_0.lab51" "Label2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab49 \
        -in $site_3_0 -x 70 -y 20 -width 197 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 260 -y 20 -width 177 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 450 -y 20 -width 158 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra45 \
        -borderwidth 10 -relief ridge -background {#595959} -height 435 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 245 
    vTcl:DefineAlias "$top.fra45" "Frame1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab52 \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {BadBlocks TT} -size 28 -weight bold} \
        -foreground {#82ffff} -text {UPDATE } 
    vTcl:DefineAlias "$site_3_0.lab52" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {BadBlocks TT} -size 28 -weight bold} \
        -foreground {#82ffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text DATA 
    vTcl:DefineAlias "$site_3_0.lab54" "Label3_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab72 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra mainpage bg4.png]] \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab72" "Label9" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but75 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#3045ff} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Sky Skunk} -size 12} -foreground {#f5fcff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text ENTER 
    vTcl:DefineAlias "$site_3_0.but75" "btn_update" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab52 \
        -in $site_3_0 -x 40 -y 30 -width 168 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 50 -y 80 -width 128 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 40 -y 190 -anchor nw -bordermode ignore 
    place $site_3_0.but75 \
        -in $site_3_0 -x 50 -y 320 -width 137 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 10 -relief ridge -background {#595959} -height 435 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 245 
    vTcl:DefineAlias "$top.fra46" "Frame1_2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {BadBlocks TT} -size 28 -weight bold} \
        -foreground {#82ffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {ONLINE } 
    vTcl:DefineAlias "$site_3_0.lab55" "Label3_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {BadBlocks TT} -size 28 -weight bold} \
        -foreground {#82ffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text SUPPORT 
    vTcl:DefineAlias "$site_3_0.lab56" "Label3_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab71 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra mainpage bg3.png]] \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab71" "Label8" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but76 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#3045ff} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Sky Skunk} -size 12} -foreground {#f5fcff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text ENTER 
    vTcl:DefineAlias "$site_3_0.but76" "btn_online" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 40 -y 30 -width 168 -height 39 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 40 -y 80 -width 168 -height 39 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 50 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.but76 \
        -in $site_3_0 -x 50 -y 320 -width 137 -height 44 -anchor nw \
        -bordermode ignore 
    frame $top.fra47 \
        -borderwidth 10 -relief ridge -background {#595959} -height 435 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$top.fra47" "Frame1_2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {BadBlocks TT} -size 28 -weight bold} \
        -foreground {#82ffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text TAX 
    vTcl:DefineAlias "$site_3_0.lab57" "Label3_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {BadBlocks TT} -size 24 -weight bold} \
        -foreground {#82ffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text CALCULATOR 
    vTcl:DefineAlias "$site_3_0.lab58" "Label3_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab70 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra mainpage bg2.png]] \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab70" "Label7" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but77 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#3045ff} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Sky Skunk} -size 12} -foreground {#f5fcff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text ENTER 
    vTcl:DefineAlias "$site_3_0.but77" "btn_calculator" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab57 \
        -in $site_3_0 -x 60 -y 30 -width 118 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 20 -y 80 -width 198 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 40 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.but77 \
        -in $site_3_0 -x 50 -y 320 -width 137 -height 44 -anchor nw \
        -bordermode ignore 
    frame $top.fra48 \
        -borderwidth 10 -relief ridge -background {#595959} -height 435 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 215 
    vTcl:DefineAlias "$top.fra48" "Frame1_2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    label $site_3_0.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {BadBlocks TT} -size 28 -weight bold} \
        -foreground {#82ffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {CONNECT } 
    vTcl:DefineAlias "$site_3_0.lab59" "Label3_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {BadBlocks TT} -size 28 -weight bold} \
        -foreground {#82ffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text TO 
    vTcl:DefineAlias "$site_3_0.lab60" "Label3_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {BadBlocks TT} -size 28 -weight bold} \
        -foreground {#82ffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text WORLD 
    vTcl:DefineAlias "$site_3_0.lab61" "Label3_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab69 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra mainpage bg1.png]] \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab69" "Label6" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but78 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#3045ff} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Sky Skunk} -size 12} -foreground {#f5fcff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text ENTER 
    vTcl:DefineAlias "$site_3_0.but78" "btn_world" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab59 \
        -in $site_3_0 -x 20 -y 30 -width 178 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 40 -y 70 -width 118 -height 39 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 40 -y 110 -width 118 -height 39 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 30 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.but78 \
        -in $site_3_0 -x 40 -y 320 -width 137 -height 44 -anchor nw \
        -bordermode ignore 
    label $top.lab63 \
        -background {#939393} -disabledforeground {#a3a3a3} \
        -font {-family {Serifa BT} -size 14 -weight bold} \
        -foreground {#0e4705} -text {Village : Kalamwadi} 
    vTcl:DefineAlias "$top.lab63" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#939393} -disabledforeground {#a3a3a3} \
        -font {-family {Serifa BT} -size 14 -weight bold} \
        -foreground {#0e4705} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {District : Sangli} 
    vTcl:DefineAlias "$top.lab64" "Label4_10" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe65 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe65" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab66 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra mainpage login3.png]] \
        -text Label 
    vTcl:DefineAlias "$top.lab66" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#939393} -disabledforeground {#a3a3a3} \
        -font {-family {Serifa BT} -size 14 -weight bold} \
        -foreground {#0e4705} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text User 
    vTcl:DefineAlias "$top.lab68" "Label4_11" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra44 \
        -in $top -x 20 -y 30 -width 635 -relwidth 0 -height 85 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 30 -y 150 -width 245 -relwidth 0 -height 435 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 280 -y 150 -width 245 -relwidth 0 -height 435 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 530 -y 150 -width 235 -relwidth 0 -height 435 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 770 -y 150 -width 215 -relwidth 0 -height 435 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 680 -y 30 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 710 -y 60 -width 154 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSe65 \
        -in $top -x 870 -y 20 -height 80 -anchor nw -bordermode inside 
    place $top.lab66 \
        -in $top -x 910 -y 30 -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 900 -y 80 -width 64 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

