#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Mar 09, 2019 10:14:06 PM IST  platform: Windows NT
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join F:/ {edd project 2019 jan} {edd project modules} {main window} login3.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Arial Black} -size 36 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family Georgia -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family Cambria -size 11 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font16
vTcl:font:add_font \
    "-family {Tw Cen MT Condensed Extra Bold} -size 22 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 925x601+294+152
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1604 882
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Main"
    vTcl:DefineAlias "$top" "Main" vTcl:Toplevel:WidgetProc "" 1
    canvas $top.can46 \
        -background {#faff69} -borderwidth 2 -closeenough 1.0 -height 713 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 1003 
    vTcl:DefineAlias "$top.can46" "Canvas1" vTcl:WidgetProc "Main" 1
    set site_3_0 $top.can46
    frame $site_3_0.fra48 \
        -borderwidth 2 -relief groove -background {#5b63d8} -height 185 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 315 
    vTcl:DefineAlias "$site_3_0.fra48" "Frame1" vTcl:WidgetProc "Main" 1
    set site_4_0 $site_3_0.fra48
    label $site_4_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b63d8} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {New Data Entry } 
    vTcl:DefineAlias "$site_4_0.lab54" "Label1" vTcl:WidgetProc "Main" 1
    button $site_4_0.but55 \
        -activebackground {#ffffff} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#5b63d8} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text ENTER 
    vTcl:DefineAlias "$site_4_0.but55" "newdata" vTcl:WidgetProc "Main" 1
    place $site_4_0.lab54 \
        -in $site_4_0 -x 60 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.but55 \
        -in $site_4_0 -x 120 -y 100 -width 77 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra59 \
        -borderwidth 2 -relief groove -background {#5b63d8} -height 185 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 315 
    vTcl:DefineAlias "$site_3_0.fra59" "Frame1_3" vTcl:WidgetProc "Main" 1
    set site_4_0 $site_3_0.fra59
    label $site_4_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b63d8} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Open The Workspace} 
    vTcl:DefineAlias "$site_4_0.lab54" "Label1_4" vTcl:WidgetProc "Main" 1
    button $site_4_0.but55 \
        -activebackground {#ffffff} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#5b63d8} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text ENTER 
    vTcl:DefineAlias "$site_4_0.but55" "openworkspace" vTcl:WidgetProc "Main" 1
    frame $site_4_0.fra60 \
        -borderwidth 2 -relief groove -background {#5b63d8} -height 185 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 315 
    vTcl:DefineAlias "$site_4_0.fra60" "Frame1_6" vTcl:WidgetProc "Main" 1
    set site_5_0 $site_4_0.fra60
    label $site_5_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b63d8} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {New Data Entry } 
    vTcl:DefineAlias "$site_5_0.lab54" "Label1_7" vTcl:WidgetProc "Main" 1
    button $site_5_0.but55 \
        -activebackground {#ffffff} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#5b63d8} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text ENTER 
    vTcl:DefineAlias "$site_5_0.but55" "Button1_8" vTcl:WidgetProc "Main" 1
    place $site_5_0.lab54 \
        -in $site_5_0 -x 60 -y 30 -anchor nw -bordermode ignore 
    place $site_5_0.but55 \
        -in $site_5_0 -x 120 -y 100 -width 77 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab54 \
        -in $site_4_0 -x 30 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.but55 \
        -in $site_4_0 -x 120 -y 100 -width 77 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.fra60 \
        -in $site_4_0 -x -110 -y 310 -width 315 -height 185 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra62 \
        -borderwidth 2 -relief groove -background {#5b63d8} -height 185 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 315 
    vTcl:DefineAlias "$site_3_0.fra62" "Frame1_12" vTcl:WidgetProc "Main" 1
    set site_4_0 $site_3_0.fra62
    label $site_4_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b63d8} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {View All Entries} 
    vTcl:DefineAlias "$site_4_0.lab54" "Label1_13" vTcl:WidgetProc "Main" 1
    button $site_4_0.but55 \
        -activebackground {#ffffff} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#5b63d8} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text ENTER 
    vTcl:DefineAlias "$site_4_0.but55" "viewentry" vTcl:WidgetProc "Main" 1
    place $site_4_0.lab54 \
        -in $site_4_0 -x 60 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.but55 \
        -in $site_4_0 -x 120 -y 100 -width 77 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra64 \
        -borderwidth 2 -relief groove -background {#5b63d8} -height 185 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 315 
    vTcl:DefineAlias "$site_3_0.fra64" "Frame1_13" vTcl:WidgetProc "Main" 1
    set site_4_0 $site_3_0.fra64
    label $site_4_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#5b63d8} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Extra Features} 
    vTcl:DefineAlias "$site_4_0.lab54" "Label1_14" vTcl:WidgetProc "Main" 1
    button $site_4_0.but55 \
        -activebackground {#ffffff} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#5b63d8} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text ENTER 
    vTcl:DefineAlias "$site_4_0.but55" "extra" vTcl:WidgetProc "Main" 1
    place $site_4_0.lab54 \
        -in $site_4_0 -x 70 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.but55 \
        -in $site_4_0 -x 120 -y 100 -width 77 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $site_3_0.lab43 \
        -background {#faff69} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#ff351f} \
        -text eTAX 
    vTcl:DefineAlias "$site_3_0.lab43" "Label2" vTcl:WidgetProc "Main" 1
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#faff69} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#201ad8} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 2019 
    vTcl:DefineAlias "$site_3_0.lab44" "Label2_1" vTcl:WidgetProc "Main" 1
    label $site_3_0.lab46 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} {main window} login3.png]] \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab46" "Label3" vTcl:WidgetProc "Main" 1
    label $site_3_0.lab48 \
        -background {#faff69} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -text {Hello user !!!} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label4" vTcl:WidgetProc "Main" 1
    label $site_3_0.lab49 \
        -background {#faff69} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} -text {e-tax 2019} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label5" vTcl:WidgetProc "Main" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#faff69} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {v 1.0.2} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label5_2" vTcl:WidgetProc "Main" 1
    button $site_3_0.but53 \
        -activebackground {#ffffff} -activeforeground {#000000} \
        -background {#5b63d8} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font16,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text {LOG OUT} 
    vTcl:DefineAlias "$site_3_0.but53" "logout" vTcl:WidgetProc "Main" 1
    button $site_3_0.but54 \
        -activebackground {#ffffff} -activeforeground {#000000} \
        -background {#5b63d8} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font16,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text EXIT 
    vTcl:DefineAlias "$site_3_0.but54" "exit" vTcl:WidgetProc "Main" 1
    place $site_3_0.fra48 \
        -in $site_3_0 -x 150 -y 230 -width 315 -relwidth 0 -height 185 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra59 \
        -in $site_3_0 -x 570 -y 230 -width 315 -height 185 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra62 \
        -in $site_3_0 -x 150 -y 470 -width 315 -height 185 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra64 \
        -in $site_3_0 -x 570 -y 470 -width 315 -height 185 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 350 -y 120 -width 170 -relwidth 0 -height 74 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 500 -y 120 -width 170 -height 74 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 880 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 860 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 50 -y 650 -width 59 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 50 -y 670 -width 59 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 70 -y 110 -width 77 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 70 -y 160 -width 77 -height 34 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can46 \
        -in $top -x -40 -y -90 -width 1003 -relwidth 0 -height 713 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

