#############################################################################
# Generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#  Apr 22, 2019 02:42:25 PM +0530  platform: Windows NT
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra {modifiocation main page} access.png]} {user image} user {}}
        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra {modifiocation main page} delete1.png]} {user image} user {}}
        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra {modifiocation main page} updatepic1.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Rockwell Extra} -size 40 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Rage Italic} -size 19 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {Rockwell Extra} -size 28 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {Segoe UI Black} -size 23 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
vTcl:font:add_font \
    "-family Postmaster -size 13 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font16
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#727272} 
    wm focusmodel $top passive
    wm geometry $top 990x650+274+133
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1596 873
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "e-TAX 2019"
    vTcl:DefineAlias "$top" "e-TAX 2019" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 10 -relief ridge -background {#595959} -height 145 \
        -width 835 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "e-TAX 2019" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Extra} -size 40 -weight bold} \
        -foreground {#0d4dff} -text {eTAX } 
    vTcl:DefineAlias "$site_3_0.lab44" "Label1" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Extra} -size 40 -weight bold} \
        -foreground {#ff2b0a} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 2019 
    vTcl:DefineAlias "$site_3_0.lab45" "Label1_1" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab47 \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rage Italic} -size 19 -slant italic} \
        -foreground {#f7ff0a} -text {working for you} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label2" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Extra} -size 28 -weight bold} \
        -foreground {#5faa14} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {UPDATE DATABASE} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1_2" vTcl:WidgetProc "e-TAX 2019" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 30 -y 30 -width 196 -relwidth 0 -height 59 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 210 -y 30 -width 146 -relwidth 0 -height 59 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 110 -y 90 -width 184 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 360 -y 30 -width 446 -relwidth 0 -height 69 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra49 \
        -borderwidth 10 -relief ridge -background {#595959} -height 345 \
        -width 325 
    vTcl:DefineAlias "$top.fra49" "Frame2" vTcl:WidgetProc "e-TAX 2019" 1
    set site_3_0 $top.fra49
    label $site_3_0.lab50 \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI Black} -size 23 -weight bold} \
        -foreground {#efff0f} -text {MODIFY DATA} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label3" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab51 \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Postmaster} -size 13} -foreground {#4cad1c} \
        -text {CLICK HERE TO UPDATE } 
    vTcl:DefineAlias "$site_3_0.lab51" "Label4" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Postmaster} -size 13} -foreground {#4cad1c} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text DATA 
    vTcl:DefineAlias "$site_3_0.lab52" "Label4_3" vTcl:WidgetProc "e-TAX 2019" 1
    button $site_3_0.but55 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra {modifiocation main page} updatepic1.png]] \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but55" "btn_modify" vTcl:WidgetProc "e-TAX 2019" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 40 -y 220 -width 234 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 50 -y 270 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 110 -y 290 -width 83 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 70 -y 20 -width 186 -relwidth 0 -height 186 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra53 \
        -borderwidth 10 -relief ridge -background {#595959} -height 345 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 325 
    vTcl:DefineAlias "$top.fra53" "Frame2_4" vTcl:WidgetProc "e-TAX 2019" 1
    set site_3_0 $top.fra53
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI Black} -size 23 -weight bold} \
        -foreground {#efff0f} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {DELETE DATA} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label3_5" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Postmaster} -size 13} -foreground {#4cad1c} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {CLICK HERE TO DELETE } 
    vTcl:DefineAlias "$site_3_0.lab51" "Label4_6" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Postmaster} -size 13} -foreground {#4cad1c} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text DATA 
    vTcl:DefineAlias "$site_3_0.lab52" "Label4_4" vTcl:WidgetProc "e-TAX 2019" 1
    button $site_3_0.but56 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra {modifiocation main page} delete1.png]] \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but56" "btn_delete" vTcl:WidgetProc "e-TAX 2019" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 40 -y 220 -width 234 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 50 -y 270 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 110 -y 290 -width 83 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 60 -y 60 -anchor nw -bordermode ignore 
    frame $top.fra54 \
        -borderwidth 10 -relief ridge -background {#595959} -height 345 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 325 
    vTcl:DefineAlias "$top.fra54" "Frame2_5" vTcl:WidgetProc "e-TAX 2019" 1
    set site_3_0 $top.fra54
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI Black} -size 23 -weight bold} \
        -foreground {#efff0f} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text PERMISSION 
    vTcl:DefineAlias "$site_3_0.lab50" "Label3_6" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Postmaster} -size 13} -foreground {#4cad1c} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {CLICK HERE TO ASK FOR } 
    vTcl:DefineAlias "$site_3_0.lab51" "Label4_7" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Postmaster} -size 13} -foreground {#4cad1c} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text PERMISSION 
    vTcl:DefineAlias "$site_3_0.lab52" "Label4_4" vTcl:WidgetProc "e-TAX 2019" 1
    button $site_3_0.but57 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra {modifiocation main page} access.png]] \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but57" "btn_access" vTcl:WidgetProc "e-TAX 2019" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 40 -y 220 -width 234 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 50 -y 270 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 110 -y 290 -width 103 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but57 \
        -in $site_3_0 -x 60 -y 60 -anchor nw -bordermode ignore 
    button $top.but58 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#264aff} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text EXIT 
    vTcl:DefineAlias "$top.but58" "btn_exit" vTcl:WidgetProc "e-TAX 2019" 1
    button $top.but59 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#264aff} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text BACK 
    vTcl:DefineAlias "$top.but59" "btn_back" vTcl:WidgetProc "e-TAX 2019" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 90 -y 30 -width 835 -relwidth 0 -height 145 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 10 -y 240 -width 325 -relwidth 0 -height 345 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra53 \
        -in $top -x 330 -y 240 -width 325 -height 345 -anchor nw \
        -bordermode ignore 
    place $top.fra54 \
        -in $top -x 650 -y 240 -width 325 -height 345 -anchor nw \
        -bordermode ignore 
    place $top.but58 \
        -in $top -x 860 -y 190 -width 90 -relwidth 0 -height 40 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 740 -y 190 -width 90 -height 40 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

