#############################################################################
# Generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#  Apr 25, 2019 02:50:13 PM +0530  platform: Windows NT
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra {online support} {2019-04-25 14_03_03-Downloads.png}]} {user image} user {}}
        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra {online support} facebook-logo-png-5a35528eaa4f08.7998622015134439826976.png]} {user image} user {}}
        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra {online support} icon_weebly.com_bot_02e090.png]} {user image} user {}}
        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra {online support} online2.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {SF Distant Galaxy} -size 13 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family Rockwell -size 11 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font14
vTcl:font:add_font \
    "-family Rockwell -size 17 -weight normal -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font15
vTcl:font:add_font \
    "-family {Franklin Gothic Demi Cond} -size 36 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font17
vTcl:font:add_font \
    "-family {Franklin Gothic Demi Cond} -size 16 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font18
vTcl:font:add_font \
    "-family {Swatch it} -size 11 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font20
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#727272} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1162x780+138+34
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1596 873
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "e-TAX 2019"
    vTcl:DefineAlias "$top" "e-TAX 2019" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 10 -relief ridge -background {#595959} -height 145 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 775 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "e-TAX 2019" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Extra} -size 40 -weight bold} \
        -foreground {#0d4dff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {eTAX } 
    vTcl:DefineAlias "$site_3_0.lab44" "Label1" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Extra} -size 40 -weight bold} \
        -foreground {#ff2b0a} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 2019 
    vTcl:DefineAlias "$site_3_0.lab45" "Label1_1" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rage Italic} -size 19 -slant italic} \
        -foreground {#f7ff0a} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {working for you} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label2" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Extra} -size 28 -weight bold} \
        -foreground {#5faa14} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Online Support} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1_2" vTcl:WidgetProc "e-TAX 2019" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 30 -y 30 -width 196 -relwidth 0 -height 59 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 210 -y 30 -width 146 -relwidth 0 -height 59 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 110 -y 90 -width 184 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 360 -y 30 -width 356 -relwidth 0 -height 69 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra44 \
        -borderwidth 10 -relief ridge -background {#595959} -height 355 \
        -width 535 
    vTcl:DefineAlias "$top.fra44" "Frame2" vTcl:WidgetProc "e-TAX 2019" 1
    set site_3_0 $top.fra44
    label $site_3_0.lab71 \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Franklin Gothic Demi Cond} -size 36} \
        -foreground {#ff9e1f} -text {REPORT A BUG} 
    vTcl:DefineAlias "$site_3_0.lab71" "Label6" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab73 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Franklin Gothic Demi Cond} -size 16} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Village :} 
    vTcl:DefineAlias "$site_3_0.lab73" "Label6_5" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab74 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Franklin Gothic Demi Cond} -size 16} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {User Name :} 
    vTcl:DefineAlias "$site_3_0.lab74" "Label6_6" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab75 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Franklin Gothic Demi Cond} -size 16} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {Query :} 
    vTcl:DefineAlias "$site_3_0.lab75" "Label6_6" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab76 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Franklin Gothic Demi Cond} -size 16} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Product ID :} 
    vTcl:DefineAlias "$site_3_0.lab76" "Label6_6" vTcl:WidgetProc "e-TAX 2019" 1
    entry $site_3_0.ent77 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent77" "txt_village" vTcl:WidgetProc "e-TAX 2019" 1
    entry $site_3_0.ent78 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent78" "txt_username" vTcl:WidgetProc "e-TAX 2019" 1
    entry $site_3_0.ent79 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent79" "txt_productid" vTcl:WidgetProc "e-TAX 2019" 1
    entry $site_3_0.ent81 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent81" "txt_query" vTcl:WidgetProc "e-TAX 2019" 1
    button $site_3_0.but94 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#ff350d} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Swatch it} -size 11 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Submit 
    vTcl:DefineAlias "$site_3_0.but94" "btn_submit1" vTcl:WidgetProc "e-TAX 2019" 1
    place $site_3_0.lab71 \
        -in $site_3_0 -x 120 -y 20 -width 284 -relwidth 0 -height 49 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 30 -y 90 -width 94 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 30 -y 130 -width 94 -height 39 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 30 -y 210 -width 94 -height 39 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 30 -y 170 -width 94 -height 39 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent77 \
        -in $site_3_0 -x 150 -y 100 -width 344 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent78 \
        -in $site_3_0 -x 150 -y 140 -width 344 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent79 \
        -in $site_3_0 -x 150 -y 180 -width 344 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent81 \
        -in $site_3_0 -x 150 -y 220 -width 344 -relwidth 0 -height 70 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but94 \
        -in $site_3_0 -x 390 -y 300 -width 80 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra45 \
        -borderwidth 10 -relief ridge -background {#595959} -height 355 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 515 
    vTcl:DefineAlias "$top.fra45" "Frame2_1" vTcl:WidgetProc "e-TAX 2019" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab84 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Franklin Gothic Demi Cond} -size 36} \
        -foreground {#ff9e1f} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Give Rating} 
    vTcl:DefineAlias "$site_3_0.lab84" "Label6_11" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab85 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Franklin Gothic Demi Cond} -size 16} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {UI :} 
    vTcl:DefineAlias "$site_3_0.lab85" "Label6_6" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab86 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Franklin Gothic Demi Cond} -size 16} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Server Connectivity :} 
    vTcl:DefineAlias "$site_3_0.lab86" "Label6_7" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab87 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Franklin Gothic Demi Cond} -size 16} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Costomer Care Service :} 
    vTcl:DefineAlias "$site_3_0.lab87" "Label6_7" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab88 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Franklin Gothic Demi Cond} -size 16} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Overall Ratings:} 
    vTcl:DefineAlias "$site_3_0.lab88" "Label6_7" vTcl:WidgetProc "e-TAX 2019" 1
    spinbox $site_3_0.spi95 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#a3a5a8} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi95" "spin1" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab97 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell} -size 11 -slant italic} \
        -foreground {#f7ff14} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Give Out of 5} 
    vTcl:DefineAlias "$site_3_0.lab97" "Label5_4" vTcl:WidgetProc "e-TAX 2019" 1
    spinbox $site_3_0.spi99 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#a3a5a8} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi99" "spin4" vTcl:WidgetProc "e-TAX 2019" 1
    spinbox $site_3_0.spi100 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#a3a5a8} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi100" "spin3" vTcl:WidgetProc "e-TAX 2019" 1
    spinbox $site_3_0.spi101 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#a3a5a8} -disabledforeground {#a3a3a3} \
        -font TkTextFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi101" "spin2" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab102 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Franklin Gothic Demi Cond} -size 36} \
        -foreground {#ff9e1f} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Write A Review } 
    vTcl:DefineAlias "$site_3_0.lab102" "Label6_9" vTcl:WidgetProc "e-TAX 2019" 1
    entry $site_3_0.ent103 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent103" "txt_review" vTcl:WidgetProc "e-TAX 2019" 1
    button $site_3_0.but104 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#ff350d} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Swatch it} -size 11 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Submit 
    vTcl:DefineAlias "$site_3_0.but104" "btn_submit2" vTcl:WidgetProc "e-TAX 2019" 1
    place $site_3_0.lab84 \
        -in $site_3_0 -x 110 -y 10 -width 284 -height 49 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab85 \
        -in $site_3_0 -x 60 -y 80 -width 94 -height 39 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab86 \
        -in $site_3_0 -x 30 -y 110 -width 174 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab87 \
        -in $site_3_0 -x 10 -y 140 -width 204 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab88 \
        -in $site_3_0 -x 30 -y 170 -width 154 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi95 \
        -in $site_3_0 -x 280 -y 90 -width 75 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab97 \
        -in $site_3_0 -x 180 -y 60 -width 152 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi99 \
        -in $site_3_0 -x 280 -y 180 -width 75 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi100 \
        -in $site_3_0 -x 280 -y 150 -width 75 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi101 \
        -in $site_3_0 -x 280 -y 120 -width 75 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab102 \
        -in $site_3_0 -x 130 -y 210 -width 284 -height 49 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent103 \
        -in $site_3_0 -x 40 -y 260 -width 414 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but104 \
        -in $site_3_0 -x 210 -y 300 -width 80 -height 34 -anchor nw \
        -bordermode ignore 
    label $top.lab46 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra {online support} online2.png]] \
        -text Label 
    vTcl:DefineAlias "$top.lab46" "Label3" vTcl:WidgetProc "e-TAX 2019" 1
    frame $top.fra47 \
        -borderwidth 10 -relief ridge -background {#595959} -height 175 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 385 
    vTcl:DefineAlias "$top.fra47" "Frame2_2" vTcl:WidgetProc "e-TAX 2019" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab49 \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {SF Distant Galaxy} -size 13} -foreground {#ffff12} \
        -text {Contact } 
    vTcl:DefineAlias "$site_3_0.lab49" "Label4" vTcl:WidgetProc "e-TAX 2019" 1
    button $site_3_0.but50 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra {online support} facebook-logo-png-5a35528eaa4f08.7998622015134439826976.png]] \
        -overrelief raised -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but50" "btn_facebook" vTcl:WidgetProc "e-TAX 2019" 1
    button $site_3_0.but51 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra {online support} icon_weebly.com_bot_02e090.png]] \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but51" "btn_website" vTcl:WidgetProc "e-TAX 2019" 1
    button $site_3_0.but52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra {online support} {2019-04-25 14_03_03-Downloads.png}]] \
        -pady 0 -text Button 
    vTcl:DefineAlias "$site_3_0.but52" "btn_call" vTcl:WidgetProc "e-TAX 2019" 1
    place $site_3_0.lab49 \
        -in $site_3_0 -x 150 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 40 -y 60 -width 96 -relwidth 0 -height 91 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 160 -y 60 -width 86 -relwidth 0 -height 86 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 270 -y 60 -width 91 -relwidth 0 -height 92 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra61 \
        -borderwidth 10 -relief ridge -background {#595959} -height 195 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 345 
    vTcl:DefineAlias "$top.fra61" "Frame2_2" vTcl:WidgetProc "e-TAX 2019" 1
    set site_3_0 $top.fra61
    label $site_3_0.lab62 \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell} -size 17 -slant italic} \
        -foreground {#1fff0f} -text {::: Developers :::} 
    vTcl:DefineAlias "$site_3_0.lab62" "Label5" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell} -size 11 -slant italic} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Pranesh Kulkarni} 
    vTcl:DefineAlias "$site_3_0.lab63" "Label5_3" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell} -size 11 -slant italic} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Prathamesh Dhasade} 
    vTcl:DefineAlias "$site_3_0.lab66" "Label5_4" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell} -size 11 -slant italic} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Anjali Gayakwad} 
    vTcl:DefineAlias "$site_3_0.lab67" "Label5_4" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell} -size 11 -slant italic} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Shraddha Kshirsagar} 
    vTcl:DefineAlias "$site_3_0.lab68" "Label5_4" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell} -size 11 -slant italic} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Ankita Chirame} 
    vTcl:DefineAlias "$site_3_0.lab69" "Label5_4" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab70 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell} -size 11 -slant italic} -foreground aqua \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Anamika Rathod} 
    vTcl:DefineAlias "$site_3_0.lab70" "Label5_4" vTcl:WidgetProc "e-TAX 2019" 1
    place $site_3_0.lab62 \
        -in $site_3_0 -x 80 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 90 -y 40 -width 152 -relwidth 0 -height 32 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 90 -y 110 -width 152 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 90 -y 130 -width 152 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 90 -y 150 -width 152 -height 32 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 90 -y 90 -width 152 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 90 -y 70 -width 152 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but105 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#3045ff} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Swatch it} -size 11 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Exit 
    vTcl:DefineAlias "$top.but105" "btn_submit2_11" vTcl:WidgetProc "e-TAX 2019" 1
    button $top.but106 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#2ba30d} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Swatch it} -size 11 -weight bold} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Back 
    vTcl:DefineAlias "$top.but106" "btn_back" vTcl:WidgetProc "e-TAX 2019" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 190 -y 20 -width 775 -relwidth 0 -height 145 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra44 \
        -in $top -x 60 -y 200 -width 535 -relwidth 0 -height 355 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 610 -y 200 -width 515 -relwidth 0 -height 355 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 40 -y 570 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 390 -y 570 -width 385 -relwidth 0 -height 175 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra61 \
        -in $top -x 790 -y 570 -width 345 -relwidth 0 -height 195 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but105 \
        -in $top -x 1010 -y 90 -width 90 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but106 \
        -in $top -x 1010 -y 40 -width 90 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

