#############################################################################
# Generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#  Apr 22, 2019 04:53:53 PM +0530  platform: Windows NT
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join F:/ {edd project 2019 jan} {edd project modules} extra {mid .............. delete} delete1.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Swatch it} -size 16 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {Segoe UI Black} -size 13 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {Shonar Bangla} -size 22 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font14
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background {#727272} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 843x469+274+133
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1596 873
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "e-TAX 2019"
    vTcl:DefineAlias "$top" "e-TAX 2019" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 10 -relief ridge -background {#595959} -height 145 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 705 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "e-TAX 2019" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Extra} -size 40 -weight bold} \
        -foreground {#0d4dff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {eTAX } 
    vTcl:DefineAlias "$site_3_0.lab44" "Label1" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Extra} -size 40 -weight bold} \
        -foreground {#ff2b0a} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 2019 
    vTcl:DefineAlias "$site_3_0.lab45" "Label1_1" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rage Italic} -size 19 -slant italic} \
        -foreground {#f7ff0a} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {working for you} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label2" vTcl:WidgetProc "e-TAX 2019" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -disabledforeground {#a3a3a3} \
        -font {-family {Rockwell Extra} -size 28 -weight bold} \
        -foreground {#5faa14} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {delete DATA} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1_2" vTcl:WidgetProc "e-TAX 2019" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 30 -y 30 -width 196 -relwidth 0 -height 59 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 210 -y 30 -width 146 -relwidth 0 -height 59 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 110 -y 90 -width 184 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 370 -y 30 -width 306 -relwidth 0 -height 69 \
        -relheight 0 -anchor nw -bordermode ignore 
    set site_3_0 $top.m43
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    label $top.lab44 \
        -background {#727272} -disabledforeground {#a3a3a3} \
        -font {-family {Swatch it} -size 16} -foreground {#f7ff1c} \
        -text {Village Name :} 
    vTcl:DefineAlias "$top.lab44" "Label3" vTcl:WidgetProc "e-TAX 2019" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#727272} -disabledforeground {#a3a3a3} \
        -font {-family {Swatch it} -size 16} -foreground {#f7ff1c} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {UID Number :} 
    vTcl:DefineAlias "$top.lab45" "Label3_1" vTcl:WidgetProc "e-TAX 2019" 1
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#727272} -disabledforeground {#a3a3a3} \
        -font {-family {Swatch it} -size 16} -foreground {#f7ff1c} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {Name  :} 
    vTcl:DefineAlias "$top.lab46" "Label3_2" vTcl:WidgetProc "e-TAX 2019" 1
    entry $top.ent47 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent47" "txt_villagename" vTcl:WidgetProc "e-TAX 2019" 1
    entry $top.ent48 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent48" "txt_uidnumber" vTcl:WidgetProc "e-TAX 2019" 1
    entry $top.ent49 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent49" "txt_name" vTcl:WidgetProc "e-TAX 2019" 1
    label $top.lab50 \
        -background {#d9d9d9} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -image [vTcl:image:get_image [file join F:/ {edd project 2019 jan} {edd project modules} extra {mid .............. delete} delete1.png]] \
        -relief raised -text Label 
    vTcl:DefineAlias "$top.lab50" "Label4" vTcl:WidgetProc "e-TAX 2019" 1
    button $top.but52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#3920d8} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI Black} -size 13 -weight bold} \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {I Wish To Continue} 
    vTcl:DefineAlias "$top.but52" "btn_submit" vTcl:WidgetProc "e-TAX 2019" 1
    label $top.lab53 \
        -background {#727272} -disabledforeground {#a3a3a3} \
        -font {-family {Shonar Bangla} -size 22} -foreground {#5bff3b} \
        -text {Disclaimer :  You Can Not recover the data once deleted} 
    vTcl:DefineAlias "$top.lab53" "Label5" vTcl:WidgetProc "e-TAX 2019" 1
    button $top.but54 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#ff3f0f} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI Black} -size 13 -weight bold} \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text EXIT 
    vTcl:DefineAlias "$top.but54" "btn_exit" vTcl:WidgetProc "e-TAX 2019" 1
    button $top.but55 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#3ba825} -borderwidth 10 -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI Black} -size 13 -weight bold} \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text BACK 
    vTcl:DefineAlias "$top.but55" "btn_back" vTcl:WidgetProc "e-TAX 2019" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 10 -y 10 -width 705 -relwidth 0 -height 145 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 90 -y 210 -width 186 -relwidth 0 -height 39 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 90 -y 260 -width 186 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.lab46 \
        -in $top -x 120 -y 300 -width 116 -relwidth 0 -height 39 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 310 -y 220 -width 304 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 310 -y 270 -width 304 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent49 \
        -in $top -x 310 -y 310 -width 304 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab50 \
        -in $top -x 650 -y 230 -width 174 -relwidth 0 -height 100 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 360 -y 390 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 80 -y 340 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 730 -y 90 -width 104 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 730 -y 30 -width 104 -height 44 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

